# Generated by Django 5.0.3 on 2024-09-26 02:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('funcao_membro', '0001_initial'),
        ('membro_projeto', '0002_remove_funcaomembroprojeto_categoria_funcao_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='CategoriaFuncao',
            new_name='CategoriaFuncaoMembro',
        ),
        migrations.RenameModel(
            old_name='FuncaoMembroProjeto',
            new_name='FuncaoMembro',
        ),
    ]
