# Generated by Django 5.0.3 on 2024-10-12 22:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('funcao_membro', '0001_initial'),
        ('iteracao', '0001_initial'),
        ('membro_projeto', '0003_membroprojeto_unique_membro_projeto'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='funcaomembro',
            name='unique_funcao_membro',
        ),
        migrations.AddConstraint(
            model_name='funcaomembro',
            constraint=models.UniqueConstraint(fields=('membro_projeto', 'categoria_funcao', 'iteracao', 'status'), name='unique_funcao_membro'),
        ),
    ]
