# Generated by Django 5.0.3 on 2024-11-18 20:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('funcao_membro', '0002_remove_funcaomembro_unique_funcao_membro_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='categoriafuncaomembro',
            name='cor',
            field=models.CharField(blank=True, max_length=7, null=True),
        ),
    ]
