# Generated by Django 5.0.3 on 2024-09-26 19:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('funcao_membro', '0002_rename_categoriafuncao_categoriafuncaomembro_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='funcaomembro',
            name='categoria_funcao',
            field=models.ForeignKey(blank=True, default=1, null=True, on_delete=django.db.models.deletion.PROTECT, to='funcao_membro.categoriafuncaomembro'),
        ),
    ]
