# Generated by Django 5.0.3 on 2024-10-09 22:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('funcao_membro', '0003_alter_funcaomembro_categoria_funcao'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='funcaomembro',
            name='data_inicio',
        ),
        migrations.RemoveField(
            model_name='funcaomembro',
            name='data_termino',
        ),
    ]
