# Generated by Django 5.0.3 on 2025-01-09 18:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('funcao_membro', '0003_categoriafuncaomembro_cor'),
        ('iteracao', '0009_alter_iteracao_status'),
        ('membro_projeto', '0003_membroprojeto_unique_membro_projeto'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='funcaomembro',
            name='unique_funcao_membro',
        ),
        migrations.AddConstraint(
            model_name='funcaomembro',
            constraint=models.UniqueConstraint(condition=models.Q(('status', True)), fields=('membro_projeto', 'categoria_funcao', 'iteracao'), name='unique_funcao_membro_iteracao'),
        ),
        migrations.AddConstraint(
            model_name='funcaomembro',
            constraint=models.UniqueConstraint(condition=models.Q(('iteracao__isnull', True), ('status', True)), fields=('membro_projeto', 'categoria_funcao'), name='unique_funcao_membro_no_iteracao'),
        ),
    ]
