# Generated by Django 4.2.5 on 2023-09-23 23:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Projeto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=200)),
                ('descricao', models.TextField()),
                ('status', models.CharField(choices=[('cancelado', 'Cancelado'), ('em_andamento', 'Em andamento'), ('concluido', 'Concluído')], max_length=20)),
                ('data_inicio', models.DateTimeField(verbose_name='Data Início')),
                ('data_fim', models.DateTimeField(verbose_name='Data Fim')),
            ],
        ),
    ]
