# Generated by Django 5.0.3 on 2024-11-20 23:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100, unique=True)),
                ('descricao', models.TextField(blank=True, null=True)),
                ('cor', models.CharField(max_length=7)),
                ('data_criacao', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
