# Generated by Django 4.2.5 on 2024-03-08 13:39

from django.db import migrations, models
import django.db.models.deletion
import markdownx.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('artefato', '0001_initial'),
        ('projeto', '0004_remove_projeto_membros'),
    ]

    operations = [
        migrations.CreateModel(
            name='Documento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=255)),
                ('conteudo_markdown', markdownx.models.MarkdownxField()),
                ('status', models.CharField(blank=True, choices=[('rascunho', 'Em rascunho'), ('revisao', 'Pendente de revisão'), ('aprovado', 'Aprovado')], max_length=40, null=True)),
                ('data_criacao', models.DateTimeField(auto_now_add=True)),
                ('artefato', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='artefato.artefato')),
                ('projeto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='projeto.projeto')),
            ],
        ),
    ]
