# Generated by Django 5.0.3 on 2024-03-16 13:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documento', '0001_initial'),
        ('iteracao', '0004_alter_iteracao_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='documento',
            name='conteudo_markdown',
        ),
        migrations.AddField(
            model_name='documento',
            name='caminho',
            field=models.CharField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='documento',
            name='iteracao',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='iteracao.iteracao'),
        ),
    ]
