# Generated by Django 5.0.3 on 2024-03-23 14:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documento', '0002_remove_documento_conteudo_markdown_documento_caminho_and_more'),
        ('pontuacao', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='documento',
            name='pontuacao',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='pontuacao.pontuacao'),
        ),
    ]
