version: '3'

services:
  postgres:
    image: postgres:latest
    environment:
      POSTGRES_DB: mydb
      POSTGRES_USER: myuser
      POSTGRES_PASSWORD: mypassword
    ports:
      - "5432:5432"
    networks:
      - mynetwork

  pgadmin:
    image: dpage/pgadmin4:latest
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@example.com
      PGADMIN_DEFAULT_PASSWORD: admin
      PGADMIN_LISTEN_PORT: 5050
    ports:
      - "8080:5050"
    depends_on:
      - postgres
    networks:
      - mynetwork

  backend:
    build:
      context: .
      dockerfile: ./academic_dev_flow/Dockerfile
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    environment:
      - DJANGO_SETTINGS_MODULE=academic_dev_flow.settings
    depends_on:
      - postgres
    networks:
      - mynetwork

  frontend:
    build:
      context: ./frontend/academic_dev_flow
      dockerfile: Dockerfile
    volumes:
      - ./frontend/academic_dev_flow:/app
    ports:
      - "3000:3000"
    networks:
      - mynetwork

networks:
  mynetwork:
    driver: bridge
