version: '3'

services:
  postgres:
    container_name: postgres_academic_dev_flow
    image: postgres:13
    environment:
      POSTGRES_USER: ${DATABASE_USER}
      POSTGRES_PASSWORD: ${DATABASE_PASSWORD}
      POSTGRES_DB: ${DATABASE_NAME}
    volumes:
      - postgres_data:/var/lib/postgresql/data
    restart: always
    ports:
      - "5400:5432"
    networks:
      - dev_network


  pgadmin:
    container_name: pgadmin_academic_dev_flow
    image: dpage/pgadmin4:latest
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_EMAIL}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_PASSWORD}
      PGADMIN_LISTEN_PORT: 5050
    ports:
      - "8080:5050"
    depends_on:
      - postgres
    networks:
      - dev_network

  frontend:
    container_name: client_academic_dev_flow
    image: client_academic_dev_flow:latest
    build:
      context: ./frontend/academic_dev_flow
      dockerfile: Dockerfile
    ports:
      - "3000:80"
    networks:
      - dev_network

  backend:
    container_name: api_academic_dev_flow
    image: api_academic_dev_flow:latest
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    volumes:
      - .:/backend
    env_file:
      - .env
    command: >
      sh -c "python manage.py migrate --noinput
             export DJANGO_SUPERUSER_PASSWORD=admin
             export DJANGO_SUPERUSER_USERNAME=admin
             export DJANGO_SUPERUSER_EMAIL=labensufrn@gmail.com
             python manage.py createsuperuser --noinput
             python manage.py runserver 0.0.0.0:8000"
    networks:
      - dev_network
    depends_on:
      - postgres

networks:
  dev_network:

volumes:
  postgres_data:
