# Generated by Django 5.0.3 on 2024-09-25 12:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('iteracao', '0001_initial'),
        ('pontuacao', '0001_initial'),
        ('projeto', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Artefato',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=255)),
                ('status', models.CharField(blank=True, choices=[('criado', 'Criado'), ('rascunho', 'Em rascunho'), ('revisao', 'Pendente de revisão'), ('aprovado', 'Aprovado'), ('finalizado', 'Finalizado')], default='criado', max_length=40, null=True)),
                ('data_criacao', models.DateTimeField(auto_now_add=True, null=True)),
                ('descricao', models.TextField(blank=True, null=True)),
                ('id_file', models.CharField(blank=True, null=True)),
                ('path_file', models.CharField(blank=True, null=True)),
                ('iteracao', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='iteracao.iteracao')),
                ('pontuacao', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='pontuacao.pontuacao')),
                ('projeto', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='projeto.projeto')),
            ],
        ),
    ]
