# Generated by Django 5.0.3 on 2024-10-06 17:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('artefato', '0001_initial'),
        ('membro_projeto', '0002_remove_funcaomembroprojeto_categoria_funcao_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='artefato',
            old_name='id_file',
            new_name='id_content',
        ),
        migrations.RenameField(
            model_name='artefato',
            old_name='path_file',
            new_name='url',
        ),
        migrations.AddField(
            model_name='artefato',
            name='membros',
            field=models.ManyToManyField(blank=True, to='membro_projeto.membroprojeto'),
        ),
        migrations.AddField(
            model_name='artefato',
            name='nome_content',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
