# Generated by Django 5.0.3 on 2024-04-08 12:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('artefato', '0001_initial'),
        ('iteracao', '0005_rename_gerente_iteracao_lider_alter_iteracao_status'),
        ('projeto', '0006_alter_projeto_descricao'),
    ]

    operations = [
        migrations.AddField(
            model_name='artefato',
            name='data_criacao',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='artefato',
            name='id_github',
            field=models.CharField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='artefato',
            name='iteracao',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='iteracao.iteracao'),
        ),
        migrations.AddField(
            model_name='artefato',
            name='path_github',
            field=models.CharField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='artefato',
            name='projeto',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='projeto.projeto'),
        ),
        migrations.AddField(
            model_name='artefato',
            name='status',
            field=models.CharField(blank=True, choices=[('criado', 'Criado'), ('rascunho', 'Em rascunho'), ('revisao', 'Pendente de revisão'), ('aprovado', 'Aprovado'), ('finalizado', 'Finalizado')], max_length=40, null=True),
        ),
        migrations.AlterField(
            model_name='artefato',
            name='descricao',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='artefato',
            name='nome',
            field=models.CharField(max_length=255),
        ),
    ]
