# Generated by Django 5.0.3 on 2024-04-09 16:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('artefato', '0002_artefato_data_criacao_artefato_id_github_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='artefato',
            old_name='id_github',
            new_name='id_file',
        ),
        migrations.RenameField(
            model_name='artefato',
            old_name='path_github',
            new_name='path_file',
        ),
    ]
