# Generated by Django 5.0.3 on 2024-10-06 20:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('artefato', '0002_rename_id_file_artefato_id_content_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='artefato',
            old_name='nome_content',
            new_name='path_content',
        ),
    ]
