# Generated by Django 5.0.3 on 2024-05-08 12:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('artefato', '0003_rename_id_github_artefato_id_file_and_more'),
        ('pontuacao', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='artefato',
            name='pontuacao',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='pontuacao.pontuacao'),
        ),
    ]
