# Generated by Django 5.0.3 on 2024-10-23 19:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('artefato', '0003_rename_nome_content_artefato_path_content'),
    ]

    operations = [
        migrations.AddField(
            model_name='artefato',
            name='data_termino',
            field=models.DateField(blank=True, null=True),
        ),
    ]
