# Generated by Django 5.0.3 on 2024-05-13 12:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('artefato', '0004_artefato_pontuacao'),
    ]

    operations = [
        migrations.AlterField(
            model_name='artefato',
            name='status',
            field=models.CharField(blank=True, choices=[('criado', 'Criado'), ('rascunho', 'Em rascunho'), ('revisao', 'Pendente de revisão'), ('aprovado', 'Aprovado'), ('finalizado', 'Finalizado')], default='criado', max_length=40, null=True),
        ),
    ]
