# Generated by Django 5.0.3 on 2024-11-20 21:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('artefato', '0005_alter_artefato_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='artefato',
            name='status',
            field=models.CharField(blank=True, choices=[('pendente', 'Pendente'), ('rascunho', 'Em rascunho'), ('revisao', 'Pendente de revisão'), ('aprovado', 'Aprovado'), ('finalizado', 'Finalizado'), ('cancelado', 'Cancelado')], default='pendente', max_length=40, null=True),
        ),
    ]
