# Generated by Django 5.0.3 on 2025-01-09 20:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('artefato', '0006_alter_artefato_status'),
    ]

    operations = [
        migrations.RenameField(
            model_name='artefato',
            old_name='data_termino',
            new_name='data_entrega',
        ),
        migrations.RemoveField(
            model_name='artefato',
            name='pontuacao',
        ),
    ]
