# Generated by Django 4.2.5 on 2024-02-11 18:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('membro', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='membro',
            name='grupo',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
