# Generated by Django 5.0.3 on 2024-09-20 21:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('membro', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='usuariogithub',
            old_name='nome',
            new_name='nome_github',
        ),
    ]
