# Generated by Django 5.0.3 on 2024-10-29 19:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('membro', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='membro',
            name='avatar',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
