# Generated by Django 4.2.5 on 2024-01-03 16:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('usuario', '0001_initial'),
        ('membro', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='membro',
            name='usuario',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='membro', to='usuario.usuario'),
        ),
    ]
