# Generated by Django 5.0.3 on 2024-09-22 16:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('membro', '0002_rename_nome_usuariogithub_nome_github'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='membro',
            name='github',
        ),
        migrations.AddField(
            model_name='membro',
            name='email_github',
            field=models.EmailField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='membro',
            name='nome_github',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='membro',
            name='usuario_github',
            field=models.CharField(blank=True, max_length=200, null=True, unique=True),
        ),
    ]
