# Generated by Django 5.0.3 on 2024-10-29 19:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('membro', '0002_membro_avatar'),
    ]

    operations = [
        migrations.AddField(
            model_name='membro',
            name='sexo',
            field=models.CharField(choices=[('M', 'Masculino'), ('F', 'Feminino'), ('O', 'Outro')], default='M', max_length=1),
        ),
    ]
