# Generated by Django 4.2.5 on 2024-01-03 18:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('membro', '0002_membro_usuario'),
    ]

    operations = [
        migrations.AlterField(
            model_name='membro',
            name='cpf',
            field=models.CharField(max_length=14),
        ),
        migrations.AlterField(
            model_name='membro',
            name='telefone',
            field=models.CharField(max_length=14),
        ),
    ]
