# Generated by Django 5.0.3 on 2024-04-01 17:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('membro', '0002_membro_grupo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='membro',
            name='cpf',
        ),
        migrations.RemoveField(
            model_name='membro',
            name='sexo',
        ),
        migrations.AddField(
            model_name='membro',
            name='github',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='membro',
            name='lattes',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='membro',
            name='linkedin',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
