# Generated by Django 4.2.5 on 2024-02-03 21:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('membro', '0002_alter_membro_cpf_alter_membro_telefone'),
    ]

    operations = [
        migrations.AddField(
            model_name='membro',
            name='grupo',
            field=models.CharField(default='à definir', max_length=50, null=True),
        ),
    ]
