# Generated by Django 5.0.3 on 2024-09-22 16:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('membro', '0003_remove_membro_github_membro_email_github_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UsuarioGithub',
        ),
    ]
