# Generated by Django 4.2.5 on 2024-01-03 19:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('membro', '0003_alter_membro_cpf_alter_membro_telefone'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='membro',
            name='usuario',
        ),
    ]
