# Generated by Django 5.0.3 on 2025-03-10 11:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('membro', '0004_alter_membro_data_nascimento_alter_membro_sexo_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='membro',
            name='grupo',
        ),
        migrations.AlterField(
            model_name='membro',
            name='avatar',
            field=models.ImageField(blank=True, null=True, upload_to='avatares/'),
        ),
    ]
