# Generated by Django 5.0.3 on 2024-04-11 15:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('membro', '0004_usuariogithub_remove_membro_github'),
    ]

    operations = [
        migrations.AddField(
            model_name='membro',
            name='github',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='membro.usuariogithub'),
        ),
        migrations.AlterField(
            model_name='usuariogithub',
            name='usuario_github',
            field=models.CharField(max_length=200),
        ),
    ]
