# Generated by Django 5.0.3 on 2024-09-22 16:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('membro', '0004_delete_usuariogithub'),
    ]

    operations = [
        migrations.AlterField(
            model_name='membro',
            name='grupo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='auth.group'),
        ),
    ]
