# Generated by Django 5.0.3 on 2025-01-01 17:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('membro', '0004_alter_membro_sexo_alter_membro_telefone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='membro',
            name='data_nascimento',
            field=models.DateField(blank=True, null=True, verbose_name='Data de nascimento'),
        ),
    ]
