# Generated by Django 4.2.5 on 2024-01-03 23:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('membro', '0004_remove_membro_usuario'),
    ]

    operations = [
        migrations.AlterField(
            model_name='membro',
            name='sexo',
            field=models.CharField(max_length=20),
        ),
    ]
