# Generated by Django 4.2.5 on 2024-03-06 14:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('membro_projeto', '0004_remove_membroprojeto_data_fim_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tarefa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=255)),
                ('descricao', models.TextField(null=True)),
                ('data_criacao', models.DateTimeField(auto_now_add=True)),
                ('concluida', models.BooleanField(default=False)),
                ('membro', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='membro_projeto.membroprojeto')),
            ],
        ),
    ]
