# Generated by Django 5.0.3 on 2024-09-25 12:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('categoria', '0001_initial'),
        ('iteracao', '0001_initial'),
        ('membro_projeto', '0001_initial'),
        ('projeto', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Label',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_github', models.CharField()),
                ('nome', models.CharField()),
                ('cor', models.CharField()),
                ('projeto', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='projeto.projeto')),
            ],
        ),
        migrations.CreateModel(
            name='Tarefa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=255)),
                ('data_criacao', models.DateTimeField(auto_now_add=True)),
                ('data_inicio', models.DateField(blank=True, null=True)),
                ('data_termino', models.DateField(blank=True, null=True)),
                ('status', models.CharField(choices=[('criada', 'Criada'), ('andamento', 'Em Andamento'), ('revisao', 'Em Revisão'), ('concluida', 'Concluída'), ('cancelada', 'Cancelada')], default='criada')),
                ('descricao', models.TextField(blank=True, null=True)),
                ('concluida', models.BooleanField(default=False)),
                ('tempo_gasto', models.IntegerField(default=0)),
                ('id_issue', models.BigIntegerField(blank=True, null=True)),
                ('number_issue', models.IntegerField(blank=True, null=True)),
                ('url_issue', models.URLField(blank=True, null=True)),
                ('categoria', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='categoria.categoria')),
                ('iteracao', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='iteracao.iteracao')),
                ('membros', models.ManyToManyField(blank=True, to='membro_projeto.membroprojeto')),
                ('projeto', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='projeto.projeto')),
            ],
        ),
        migrations.CreateModel(
            name='IntervaloTempo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('inicio', 'Início'), ('pausa', 'Pausa')], max_length=10)),
                ('data_hora', models.DateTimeField(auto_now_add=True)),
                ('membro_projeto', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='membro_projeto.membroprojeto')),
                ('tarefa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='intervalos', to='tarefa.tarefa')),
            ],
        ),
    ]
