# Generated by Django 4.2.5 on 2024-03-06 16:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('projeto', '0002_alter_projeto_fluxo'),
        ('tarefa', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tarefa',
            name='projeto',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='projeto.projeto'),
        ),
    ]
