# Generated by Django 5.0.3 on 2024-09-26 01:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tarefa', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Label',
        ),
    ]
