# Generated by Django 5.0.3 on 2024-10-01 02:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tarefa', '0002_delete_label'),
    ]

    operations = [
        migrations.CreateModel(
            name='CategoriaTarefa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=40)),
                ('descricao', models.TextField(blank=True, max_length=200, null=True)),
                ('cor', models.CharField(max_length=7)),
            ],
        ),
        migrations.RemoveField(
            model_name='tarefa',
            name='concluida',
        ),
        migrations.AlterField(
            model_name='tarefa',
            name='categoria',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='tarefa.categoriatarefa'),
        ),
    ]
