# Generated by Django 4.2.5 on 2024-03-06 17:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tarefa', '0002_tarefa_projeto'),
    ]

    operations = [
        migrations.AddField(
            model_name='tarefa',
            name='prazo',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='tarefa',
            name='descricao',
            field=models.TextField(blank=True, null=True),
        ),
    ]
