# Generated by Django 4.2.5 on 2024-03-06 17:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('membro_projeto', '0004_remove_membroprojeto_data_fim_and_more'),
        ('tarefa', '0003_tarefa_prazo_alter_tarefa_descricao'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tarefa',
            name='membro',
        ),
        migrations.AddField(
            model_name='tarefa',
            name='membro',
            field=models.ManyToManyField(blank=True, null=True, to='membro_projeto.membroprojeto'),
        ),
    ]
