# Generated by Django 4.2.5 on 2024-03-06 17:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('membro_projeto', '0004_remove_membroprojeto_data_fim_and_more'),
        ('tarefa', '0004_remove_tarefa_membro_tarefa_membro'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tarefa',
            name='membro',
            field=models.ManyToManyField(to='membro_projeto.membroprojeto'),
        ),
    ]
