# Generated by Django 5.0.3 on 2024-11-20 21:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tarefa', '0004_alter_tarefa_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tarefa',
            name='status',
            field=models.CharField(choices=[('pendente', 'Pendente'), ('andamento', 'Em Andamento'), ('concluida', 'Concluída'), ('atrasada', 'Em Atraso'), ('bloqueada', 'Bloqueada'), ('cancelada', 'Cancelada')], default='criada'),
        ),
    ]
