# Generated by Django 4.2.5 on 2024-03-06 18:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tarefa', '0005_alter_tarefa_membro'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tarefa',
            old_name='membro',
            new_name='membros',
        ),
    ]
