# Generated by Django 5.0.3 on 2024-11-20 23:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tags', '0001_initial'),
        ('tarefa', '0006_alter_tarefa_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='tarefa',
            name='tags',
            field=models.ManyToManyField(blank=True, to='tags.tag'),
        ),
    ]
