# Generated by Django 4.2.5 on 2024-03-07 18:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('iteracao', '0004_alter_iteracao_status'),
        ('tarefa', '0006_rename_membro_tarefa_membros'),
    ]

    operations = [
        migrations.AddField(
            model_name='tarefa',
            name='iteracao',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='iteracao.iteracao'),
        ),
    ]
