# Generated by Django 5.0.3 on 2025-01-08 23:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('iteracao', '0008_alter_iteracao_status'),
        ('tarefa', '0007_tarefa_tags'),
    ]

    operations = [
        migrations.AddField(
            model_name='tarefa',
            name='data_conclusao',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='tarefa',
            name='iteracao',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='iteracao.iteracao'),
        ),
        migrations.AlterField(
            model_name='tarefa',
            name='status',
            field=models.CharField(choices=[('pendente', 'Pendente'), ('planejada', 'Planejada'), ('andamento', 'Em Andamento'), ('concluida', 'Concluída'), ('atrasada', 'Em Atraso'), ('bloqueada', 'Bloqueada'), ('cancelada', 'Cancelada')], default='pendente'),
        ),
    ]
