# Generated by Django 5.0.3 on 2024-04-06 12:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tarefa', '0007_tarefa_iteracao'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tarefa',
            name='prazo',
        ),
        migrations.AddField(
            model_name='tarefa',
            name='data_termino',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='tarefa',
            name='status',
            field=models.CharField(choices=[('criada', 'Criada'), ('andamento', 'Em Andamento'), ('concluida', 'Concluída'), ('cancelada', 'Cancelada'), ('atrasada', 'Atrasada'), ('bloqueada', 'Bloqueada')], default='criada'),
        ),
        migrations.AddField(
            model_name='tarefa',
            name='tempo_gasto',
            field=models.IntegerField(default=0),
        ),
        migrations.CreateModel(
            name='IntervaloTempo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('inicio', 'Início'), ('pausa', 'Pausa')], max_length=10)),
                ('data_hora', models.DateTimeField(auto_now_add=True)),
                ('tarefa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='intervalos', to='tarefa.tarefa')),
            ],
        ),
    ]
