# Generated by Django 5.0.3 on 2025-01-08 23:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tarefa', '0008_tarefa_data_conclusao_alter_tarefa_iteracao_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tarefa',
            name='data_conclusao',
            field=models.DateField(blank=True, null=True),
        ),
    ]
