# Generated by Django 5.0.3 on 2024-04-06 12:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('membro_projeto', '0004_remove_membroprojeto_data_fim_and_more'),
        ('tarefa', '0008_remove_tarefa_prazo_tarefa_data_termino_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='intervalotempo',
            name='membro_projeto',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='membro_projeto.membroprojeto'),
        ),
    ]
