# Generated by Django 5.0.3 on 2025-01-09 17:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tarefa', '0009_alter_tarefa_data_conclusao'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tarefa',
            name='status',
            field=models.CharField(choices=[('pendente', 'Pendente'), ('planejamento', 'Em planejamento'), ('andamento', 'Em Andamento'), ('concluida', 'Concluída'), ('atrasada', 'Em Atraso'), ('bloqueada', 'Bloqueada'), ('cancelada', 'Cancelada')], default='pendente'),
        ),
    ]
