# Generated by Django 5.0.3 on 2024-04-07 22:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tarefa', '0010_tarefa_tipo'),
    ]

    operations = [
        migrations.AddField(
            model_name='tarefa',
            name='data_inicio',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='tarefa',
            name='data_termino',
            field=models.DateField(blank=True, null=True),
        ),
    ]
