# Generated by Django 5.0.3 on 2024-04-23 11:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tarefa', '0011_tarefa_data_inicio_alter_tarefa_data_termino'),
    ]

    operations = [
        migrations.AddField(
            model_name='tarefa',
            name='id_issue',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='tarefa',
            name='number_issue',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
