# Generated by Django 5.0.3 on 2024-04-24 18:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tarefa', '0013_label_remove_tarefa_tipo_tarefa_labels'),
    ]

    operations = [
        migrations.AddField(
            model_name='tarefa',
            name='issue_url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
