# Generated by Django 5.0.3 on 2024-04-25 12:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tarefa', '0014_tarefa_issue_url'),
    ]

    operations = [
        migrations.RenameField(
            model_name='label',
            old_name='color',
            new_name='cor',
        ),
    ]
