# Generated by Django 5.0.3 on 2024-04-27 16:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tarefa', '0016_label_projeto'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tarefa',
            name='id_issue',
            field=models.BigIntegerField(blank=True, null=True),
        ),
    ]
