# Generated by Django 5.0.3 on 2024-04-27 20:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tarefa', '0017_alter_tarefa_id_issue'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tarefa',
            old_name='issue_url',
            new_name='url_issue',
        ),
    ]
