# Generated by Django 5.0.3 on 2024-04-28 00:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('membro_projeto', '0006_alter_funcaomembroprojeto_funcao'),
        ('tarefa', '0018_rename_issue_url_tarefa_url_issue'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tarefa',
            name='labels',
            field=models.ManyToManyField(blank=True, null=True, to='tarefa.label'),
        ),
        migrations.AlterField(
            model_name='tarefa',
            name='membros',
            field=models.ManyToManyField(blank=True, null=True, to='membro_projeto.membroprojeto'),
        ),
    ]
