# Generated by Django 5.0.3 on 2024-05-03 23:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('membro_projeto', '0010_rename_funcao_funcaomembroprojetoatual_funcao_membro'),
        ('tarefa', '0019_alter_tarefa_labels_alter_tarefa_membros'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tarefa',
            name='labels',
            field=models.ManyToManyField(to='tarefa.label'),
        ),
        migrations.AlterField(
            model_name='tarefa',
            name='membros',
            field=models.ManyToManyField(to='membro_projeto.membroprojeto'),
        ),
    ]
