# Generated by Django 5.0.3 on 2024-05-05 00:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tarefa', '0020_alter_tarefa_labels_alter_tarefa_membros'),
        ('tipo', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tarefa',
            name='tipo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='tipo.tipo'),
        ),
    ]
