# Generated by Django 5.0.3 on 2024-05-19 17:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tarefa', '0021_tarefa_tipo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tarefa',
            name='labels',
        ),
    ]
