# Generated by Django 5.0.3 on 2024-05-19 17:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tarefa', '0022_remove_tarefa_labels'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tarefa',
            name='status',
            field=models.CharField(choices=[('criada', 'Criada'), ('andamento', 'Em Andamento'), ('revisao', 'Em Revisão'), ('concluida', 'Concluída'), ('cancelada', 'Cancelada')], default='criada'),
        ),
    ]
