# Generated by Django 5.0.3 on 2024-05-22 23:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('membro_projeto', '0013_alter_funcaomembroprojetoatual_data_inicio'),
        ('tarefa', '0023_alter_tarefa_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tarefa',
            name='membros',
            field=models.ManyToManyField(blank=True, null=True, to='membro_projeto.membroprojeto'),
        ),
    ]
