# Generated by Django 4.2.5 on 2024-02-11 13:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('usuario', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='grupos',
            field=models.ManyToManyField(blank=True, related_name='usuarios', to='auth.group'),
        ),
    ]
