# Generated by Django 4.2.5 on 2024-01-04 18:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('usuario', '0002_usuario_membro'),
    ]

    operations = [
        migrations.RenameField(
            model_name='usuario',
            old_name='membro',
            new_name='membro_id',
        ),
    ]
