# Generated by Django 4.2.5 on 2024-02-11 18:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('usuario', '0002_usuario_grupos'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usuario',
            name='grupos',
        ),
    ]
