# Generated by Django 4.2.5 on 2024-01-10 16:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('fluxo', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Etapa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=200)),
                ('descricao', models.TextField()),
                ('data_inicio', models.DateField(verbose_name='Data Início')),
                ('data_fim', models.DateField(verbose_name='Data Fim')),
                ('status', models.CharField(choices=[('Em andamento', 'Em andamento'), ('Concluída', 'Concluída'), ('Pendente', 'Pendente')], max_length=20)),
                ('fluxo', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='fluxo.fluxo')),
            ],
        ),
    ]
