# Generated by Django 4.2.5 on 2024-01-23 16:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('etapa', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='etapa',
            name='data_fim',
        ),
        migrations.RemoveField(
            model_name='etapa',
            name='data_inicio',
        ),
        migrations.RemoveField(
            model_name='etapa',
            name='fluxo',
        ),
        migrations.RemoveField(
            model_name='etapa',
            name='status',
        ),
    ]
