# Generated by Django 5.0.3 on 2024-11-15 14:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('etapa', '0002_etapa_created_by_etapa_data_criacao'),
    ]

    operations = [
        migrations.AlterField(
            model_name='etapa',
            name='descricao',
            field=models.TextField(blank=True, null=True),
        ),
    ]
