# Generated by Django 4.2.5 on 2024-01-24 18:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('etapa', '0003_fluxoetapa'),
    ]

    operations = [
        migrations.DeleteModel(
            name='FluxoEtapa',
        ),
    ]
