# Generated by Django 5.0.3 on 2025-03-30 17:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feedback', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feedback',
            name='tipo',
            field=models.CharField(choices=[('sugestao', 'Sugestão'), ('reclamacao', 'Reclamação'), ('bug', 'Bug'), ('nova_funcionalidade', 'Nova Funcionalidade'), ('melhoria_funcionalidade', 'Melhoria de Funcionalidade'), ('experiencia_usuario', 'Experiência do Usuário'), ('duvida_uso', 'Dúvida sobre o uso'), ('problema_acessibilidade', 'Problemas de Acessibilidade')]),
        ),
    ]
