# Generated by Django 5.0.3 on 2024-09-25 12:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('membro', '0001_initial'),
        ('projeto', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CategoriaFuncao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(default='membro', max_length=100)),
                ('descricao', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='MembroProjeto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('membro', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='membro.membro')),
                ('projeto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='projeto.projeto')),
            ],
        ),
        migrations.CreateModel(
            name='FuncaoMembroProjeto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_inicio', models.DateField(blank=True, null=True)),
                ('data_termino', models.DateField(blank=True, null=True)),
                ('status', models.BooleanField(default=True)),
                ('categoria_funcao', models.ForeignKey(blank=True, default=1, null=True, on_delete=django.db.models.deletion.CASCADE, to='membro_projeto.categoriafuncao')),
                ('membro_projeto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='membro_projeto.membroprojeto')),
            ],
        ),
    ]
