# Generated by Django 4.2.5 on 2024-01-31 00:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('membro', '0002_alter_membro_cpf_alter_membro_telefone'),
        ('projeto', '0002_alter_projeto_data_fim_alter_projeto_data_inicio'),
    ]

    operations = [
        migrations.CreateModel(
            name='MembroProjeto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('funcao', models.CharField(blank=True, max_length=40, null=True)),
                ('data_inicio', models.DateField(auto_now_add=True)),
                ('data_fim', models.DateField(blank=True, null=True)),
                ('membro', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='membro.membro')),
                ('projeto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='projeto.projeto')),
            ],
        ),
    ]
