# Generated by Django 5.0.3 on 2024-08-04 14:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('membro', '__first__'),
        ('projeto', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='FuncaoMembroProjeto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(default='membro', max_length=100)),
                ('descricao', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='FuncaoMembroProjetoAtual',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_inicio', models.DateField(blank=True, null=True)),
                ('data_termino', models.DateField(blank=True, null=True)),
                ('ativo', models.BooleanField(default=True)),
                ('funcao_membro', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='membro_projeto.funcaomembroprojeto')),
            ],
        ),
        migrations.CreateModel(
            name='MembroProjeto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('funcoes', models.ManyToManyField(through='membro_projeto.FuncaoMembroProjetoAtual', to='membro_projeto.funcaomembroprojeto')),
                ('membro', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='membro.membro')),
                ('projeto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='projeto.projeto')),
            ],
        ),
        migrations.AddField(
            model_name='funcaomembroprojetoatual',
            name='membro_projeto',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='membro_projeto.membroprojeto'),
        ),
        migrations.AddConstraint(
            model_name='funcaomembroprojetoatual',
            constraint=models.UniqueConstraint(condition=models.Q(('ativo', True)), fields=('membro_projeto',), name='unique_active_member_project'),
        ),
    ]
