# Generated by Django 4.2.5 on 2024-02-01 11:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('membro_projeto', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='membroprojeto',
            name='funcao',
            field=models.CharField(blank=True, default='À definir', max_length=40, null=True),
        ),
    ]
