# Generated by Django 5.0.3 on 2024-09-26 01:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('membro_projeto', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='funcaomembroprojeto',
            name='categoria_funcao',
        ),
        migrations.RemoveField(
            model_name='funcaomembroprojeto',
            name='membro_projeto',
        ),
        migrations.DeleteModel(
            name='CategoriaFuncao',
        ),
        migrations.DeleteModel(
            name='FuncaoMembroProjeto',
        ),
    ]
