# Generated by Django 5.0.3 on 2024-10-08 21:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('membro', '0001_initial'),
        ('membro_projeto', '0002_remove_funcaomembroprojeto_categoria_funcao_and_more'),
        ('projeto', '0001_initial'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='membroprojeto',
            constraint=models.UniqueConstraint(fields=('projeto', 'membro'), name='unique_membro_projeto'),
        ),
    ]
