# Generated by Django 4.2.5 on 2024-03-05 16:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('membro_projeto', '0003_historicomembroprojeto'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='membroprojeto',
            name='data_fim',
        ),
        migrations.RemoveField(
            model_name='membroprojeto',
            name='data_inicio',
        ),
    ]
