# Generated by Django 5.0.3 on 2024-04-06 13:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('membro_projeto', '0004_remove_membroprojeto_data_fim_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='membroprojeto',
            name='funcao',
        ),
        migrations.CreateModel(
            name='FuncaoMembroProjeto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('funcao', models.CharField(blank=True, choices=[('membro', 'Membro'), ('gerente', 'Gerente de Projeto'), ('desenvolvedor', 'Desenvolvedor de Software'), ('desenvolvedor_frontend', 'Desenvolvedor Front-End'), ('desenvolvedor_backend', 'Desenvolvedor Back-End'), ('desenvolvedor_fullstack', 'Desenvolvedor Full-Stack'), ('analista', 'Analista de Sistemas'), ('testador', 'Engenheiro de Testes'), ('design', 'Designer de UI/UX'), ('arquiteto', 'Arquiteto de Software'), ('scrum_master', 'Scrum Master'), ('product_owner', 'Product Owner'), ('dba', 'Administrador de Banco de Dados'), ('devops', 'Engenheiro DevOps'), ('analista_seguranca', 'Analista de Segurança'), ('analista_requisitos', 'Analista de Requisitos'), ('integrador', 'Integrador de Sistemas')], default='membro', null=True)),
                ('data_inicio', models.DateTimeField(auto_now_add=True)),
                ('data_termino', models.DateTimeField(blank=True, null=True)),
                ('membro_projeto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='membro_projeto.membroprojeto')),
            ],
        ),
        migrations.DeleteModel(
            name='HistoricoMembroProjeto',
        ),
    ]
