# Generated by Django 5.0.3 on 2024-04-28 00:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('membro_projeto', '0005_remove_membroprojeto_funcao_funcaomembroprojeto_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='funcaomembroprojeto',
            name='funcao',
            field=models.CharField(blank=True, choices=[('membro', 'Membro'), ('Líder', 'Líder de Projeto'), ('desenvolvedor', 'Desenvolvedor de Software'), ('desenvolvedor_frontend', 'Desenvolvedor Front-End'), ('desenvolvedor_backend', 'Desenvolvedor Back-End'), ('desenvolvedor_fullstack', 'Desenvolvedor Full-Stack'), ('analista', 'Analista de Sistemas'), ('testador', 'Engenheiro de Testes'), ('design', 'Designer de UI/UX'), ('arquiteto', 'Arquiteto de Software'), ('scrum_master', 'Scrum Master'), ('product_owner', 'Product Owner'), ('dba', 'Administrador de Banco de Dados'), ('devops', 'Engenheiro DevOps'), ('analista_seguranca', 'Analista de Segurança'), ('analista_requisitos', 'Analista de Requisitos'), ('integrador', 'Integrador de Sistemas')], default='membro', null=True),
        ),
    ]
