# Generated by Django 5.0.3 on 2024-05-02 13:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('membro_projeto', '0007_alter_funcaomembroprojeto_funcao'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='funcaomembroprojeto',
            name='data_inicio',
        ),
        migrations.RemoveField(
            model_name='funcaomembroprojeto',
            name='data_termino',
        ),
        migrations.RemoveField(
            model_name='funcaomembroprojeto',
            name='funcao',
        ),
        migrations.RemoveField(
            model_name='funcaomembroprojeto',
            name='membro_projeto',
        ),
        migrations.AddField(
            model_name='funcaomembroprojeto',
            name='descricao',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='funcaomembroprojeto',
            name='nome',
            field=models.CharField(default='membro', max_length=100),
        ),
        migrations.AddField(
            model_name='funcaomembroprojeto',
            name='status',
            field=models.CharField(choices=[('membro', 'Membro'), ('lider', 'Líder de Projeto'), ('desenvolvedor', 'Desenvolvedor de Software'), ('desenvolvedor_frontend', 'Desenvolvedor Front-End'), ('desenvolvedor_backend', 'Desenvolvedor Back-End'), ('desenvolvedor_fullstack', 'Desenvolvedor Full-Stack'), ('analista', 'Analista de Sistemas'), ('testador', 'Engenheiro de Testes'), ('design', 'Designer de UI/UX'), ('arquiteto', 'Arquiteto de Software'), ('scrum_master', 'Scrum Master'), ('product_owner', 'Product Owner'), ('dba', 'Administrador de Banco de Dados'), ('devops', 'Engenheiro DevOps'), ('analista_seguranca', 'Analista de Segurança'), ('analista_requisitos', 'Analista de Requisitos'), ('integrador', 'Integrador de Sistemas')], default='membro', max_length=100),
        ),
        migrations.CreateModel(
            name='FuncaoMembroProjetoAtual',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_inicio', models.DateTimeField(auto_now_add=True)),
                ('data_termino', models.DateTimeField(blank=True, null=True)),
                ('ativo', models.BooleanField(default=True)),
                ('funcao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='membro_projeto.funcaomembroprojeto')),
                ('membro_projeto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='membro_projeto.membroprojeto')),
            ],
            options={
                'unique_together': {('membro_projeto', 'ativo')},
            },
        ),
        migrations.AddField(
            model_name='membroprojeto',
            name='funcoes',
            field=models.ManyToManyField(through='membro_projeto.FuncaoMembroProjetoAtual', to='membro_projeto.funcaomembroprojeto'),
        ),
    ]
