# Generated by Django 5.0.3 on 2024-05-02 13:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('membro_projeto', '0008_remove_funcaomembroprojeto_data_inicio_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='funcaomembroprojeto',
            name='status',
        ),
    ]
