# Generated by Django 5.0.3 on 2024-05-03 23:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('membro_projeto', '0009_remove_funcaomembroprojeto_status'),
    ]

    operations = [
        migrations.RenameField(
            model_name='funcaomembroprojetoatual',
            old_name='funcao',
            new_name='funcao_membro',
        ),
    ]
