# Generated by Django 5.0.3 on 2024-05-03 23:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('membro_projeto', '0010_rename_funcao_funcaomembroprojetoatual_funcao_membro'),
    ]

    operations = [
        migrations.AlterField(
            model_name='funcaomembroprojetoatual',
            name='data_inicio',
            field=models.DateField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='funcaomembroprojetoatual',
            name='data_termino',
            field=models.DateField(blank=True, null=True),
        ),
    ]
