# Generated by Django 5.0.3 on 2024-05-04 16:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('membro_projeto', '0011_alter_funcaomembroprojetoatual_data_inicio_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='funcaomembroprojetoatual',
            unique_together=set(),
        ),
        migrations.AddConstraint(
            model_name='funcaomembroprojetoatual',
            constraint=models.UniqueConstraint(condition=models.Q(('ativo', True)), fields=('membro_projeto',), name='unique_active_member_project'),
        ),
    ]
