# Generated by Django 5.0.3 on 2024-05-04 18:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('membro_projeto', '0012_alter_funcaomembroprojetoatual_unique_together_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='funcaomembroprojetoatual',
            name='data_inicio',
            field=models.DateField(blank=True, null=True),
        ),
    ]
