# Generated by Django 5.0.3 on 2024-09-25 12:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('fluxo', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Projeto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=200)),
                ('descricao', models.TextField(blank=True, null=True)),
                ('status', models.CharField(choices=[('criado', 'Criado'), ('andamento', 'Em Andamento'), ('concluido', 'Concluído'), ('cancelado', 'Cancelado')], default='criado')),
                ('data_inicio', models.DateField(verbose_name='Data Início')),
                ('data_termino', models.DateField(verbose_name='Data Fim')),
                ('nome_repo', models.CharField(blank=True, max_length=200, null=True)),
                ('link_repo', models.CharField(blank=True, max_length=200, null=True)),
                ('link_site', models.CharField(blank=True, max_length=200, null=True)),
                ('token', models.CharField(blank=True, max_length=200, null=True)),
                ('fluxo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='projetos', to='fluxo.fluxo')),
            ],
        ),
    ]
