# Generated by Django 5.0.3 on 2024-11-20 20:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projeto', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projeto',
            name='status',
            field=models.CharField(choices=[('planejado', 'Planejado'), ('criado', 'Criado'), ('andamento', 'Em Andamento'), ('concluido', 'Concluído'), ('cancelado', 'Cancelado'), ('atrasado', 'Atrasado'), ('espera', 'Em espera')], default='criado'),
        ),
    ]
