# Generated by Django 4.2.5 on 2024-01-10 15:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projeto', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projeto',
            name='status',
            field=models.CharField(max_length=20),
        ),
    ]
