# Generated by Django 4.2.5 on 2024-01-11 18:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projeto', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projeto',
            name='data_fim',
            field=models.DateField(verbose_name='Data Fim'),
        ),
        migrations.AlterField(
            model_name='projeto',
            name='data_inicio',
            field=models.DateField(verbose_name='Data Início'),
        ),
    ]
