# Generated by Django 5.0.3 on 2024-09-21 22:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projeto', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='projeto',
            old_name='data_fim',
            new_name='data_termino',
        ),
    ]
