# Generated by Django 4.2.5 on 2024-02-04 19:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('fluxo', '0001_initial'),
        ('projeto', '0002_alter_projeto_data_fim_alter_projeto_data_inicio'),
    ]

    operations = [
        migrations.AddField(
            model_name='projeto',
            name='fluxo',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='fluxo', to='fluxo.fluxo'),
        ),
    ]
