# Generated by Django 5.0.3 on 2025-01-09 17:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projeto', '0002_alter_projeto_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projeto',
            name='status',
            field=models.CharField(choices=[('planejamento', 'Em Planejamento'), ('criado', 'Criado'), ('andamento', 'Em Andamento'), ('concluido', 'Concluído'), ('cancelado', 'Cancelado'), ('atrasado', 'Atrasado'), ('espera', 'Em espera')], default='criado'),
        ),
    ]
