# Generated by Django 4.2.5 on 2024-03-06 17:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('membro', '0002_membro_grupo'),
        ('projeto', '0002_alter_projeto_fluxo'),
    ]

    operations = [
        migrations.AddField(
            model_name='projeto',
            name='membros',
            field=models.ManyToManyField(to='membro.membro'),
        ),
    ]
