# Generated by Django 5.0.3 on 2025-03-30 18:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('membro', '0005_remove_membro_grupo_alter_membro_avatar'),
        ('projeto', '0003_alter_projeto_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='projeto',
            name='coordenador',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='coordenador', to='membro.membro'),
        ),
    ]
