# Generated by Django 4.2.5 on 2024-03-06 18:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projeto', '0003_projeto_membros'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='projeto',
            name='membros',
        ),
    ]
