# Generated by Django 5.0.3 on 2024-04-01 16:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projeto', '0004_remove_projeto_membros'),
    ]

    operations = [
        migrations.AddField(
            model_name='projeto',
            name='repositorio',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='projeto',
            name='site',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='projeto',
            name='token',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
