# Generated by Django 5.0.3 on 2024-04-11 15:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projeto', '0006_alter_projeto_descricao'),
    ]

    operations = [
        migrations.RenameField(
            model_name='projeto',
            old_name='repositorio',
            new_name='link_repo',
        ),
        migrations.RenameField(
            model_name='projeto',
            old_name='site',
            new_name='link_site',
        ),
        migrations.AddField(
            model_name='projeto',
            name='nome_repo',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
