# Generated by Django 4.2.5 on 2024-01-24 18:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('fluxo', '0001_initial'),
        ('etapa', '0004_delete_fluxoetapa'),
    ]

    operations = [
        migrations.CreateModel(
            name='FluxoEtapa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('etapa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='etapa.etapa')),
                ('fluxo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fluxo.fluxo')),
            ],
        ),
    ]
