# Generated by Django 5.0.3 on 2024-08-04 14:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('etapa', '0001_initial'),
        ('fluxo', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='FluxoEtapa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('etapa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='etapa.etapa')),
                ('fluxo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fluxo.fluxo')),
            ],
        ),
    ]
