# Generated by Django 4.2.5 on 2024-01-28 21:06

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('fluxo_etapa', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='fluxoetapa',
            name='data_fim',
            field=models.DateField(default=django.utils.timezone.now, verbose_name='Data Fim'),
        ),
        migrations.AddField(
            model_name='fluxoetapa',
            name='data_inicio',
            field=models.DateField(default=django.utils.timezone.now, verbose_name='Data Início'),
        ),
        migrations.AddField(
            model_name='fluxoetapa',
            name='status',
            field=models.CharField(default='Em andamento', max_length=20),
        ),
    ]
