# Generated by Django 5.0.3 on 2026-04-28 23:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("fluxo_etapa", "0002_fluxoetapa_created_by_fluxoetapa_data_adicao_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="fluxoetapa",
            name="posicao_x",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="fluxoetapa",
            name="posicao_y",
            field=models.FloatField(blank=True, null=True),
        ),
    ]
