# Generated by Django 5.0.3 on 2026-04-28 23:32

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("fluxo", "0002_fluxo_created_by_fluxo_data_criacao"),
        ("fluxo_etapa", "0003_fluxoetapa_posicao_x_fluxoetapa_posicao_y"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="TransicaoFluxo",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("label", models.CharField(blank=True, max_length=100, null=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "destino",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="entradas",
                        to="fluxo_etapa.fluxoetapa",
                    ),
                ),
                (
                    "fluxo",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="fluxo.fluxo"
                    ),
                ),
                (
                    "origem",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="saidas",
                        to="fluxo_etapa.fluxoetapa",
                    ),
                ),
            ],
        ),
    ]
