# Generated by Django 5.0.3 on 2024-10-26 19:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fluxo_etapa', '0001_initial'),
        ('release', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='release',
            name='etapa',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='fluxo_etapa.fluxoetapa'),
        ),
    ]
