# Generated by Django 5.0.3 on 2024-10-26 19:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('membro_projeto', '0003_membroprojeto_unique_membro_projeto'),
        ('release', '0002_release_etapa'),
    ]

    operations = [
        migrations.AddField(
            model_name='release',
            name='responsavel',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='membro_projeto.membroprojeto'),
        ),
    ]
