# Generated by Django 5.0.3 on 2024-10-26 19:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('release', '0003_release_responsavel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='release',
            name='descricao',
            field=models.TextField(blank=True, null=True),
        ),
    ]
