# Generated by Django 5.0.3 on 2025-01-01 17:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('release', '0007_alter_release_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='release',
            name='status',
            field=models.CharField(choices=[('pendente', 'Pendente'), ('andamento', 'Em Andamento'), ('concluida', 'Concluída'), ('cancelada', 'Cancelada'), ('bloqueada', 'Bloqueada')], default='pendente', max_length=20),
        ),
    ]
