# Generated by Django 4.2.5 on 2024-03-04 22:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('projeto', '0002_alter_projeto_fluxo'),
    ]

    operations = [
        migrations.CreateModel(
            name='Iteracao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=200)),
                ('numero', models.IntegerField()),
                ('descricao', models.TextField(null=True)),
                ('status', models.CharField()),
                ('data_inicio', models.DateField()),
                ('data_fim', models.DateField()),
                ('projeto', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='projeto', to='projeto.projeto')),
            ],
        ),
    ]
