# Generated by Django 4.2.5 on 2024-03-04 22:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('membro_projeto', '0001_initial'),
        ('fluxo_etapa', '0001_initial'),
        ('iteracao', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='iteracao',
            name='fase',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='fluxo_etapa.fluxoetapa'),
        ),
        migrations.AddField(
            model_name='iteracao',
            name='gerente',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='membro_projeto.membroprojeto'),
        ),
    ]
