# Generated by Django 4.2.5 on 2024-03-04 23:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('projeto', '0002_alter_projeto_fluxo'),
        ('iteracao', '0002_iteracao_fase_iteracao_gerente'),
    ]

    operations = [
        migrations.AlterField(
            model_name='iteracao',
            name='projeto',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='iteracoes', to='projeto.projeto'),
        ),
        migrations.AlterField(
            model_name='iteracao',
            name='status',
            field=models.CharField(choices=[('planejamento', 'Em Planejamento'), ('andamento', 'Em Andamento'), ('concluida', 'Concluída')], default='planejamento', max_length=20),
        ),
    ]
