# Generated by Django 5.0.3 on 2024-10-26 18:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('iteracao', '0002_rename_numero_iteracao_ordem_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='release',
            name='projeto',
        ),
    ]
