# Generated by Django 4.2.5 on 2024-03-04 23:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('iteracao', '0003_alter_iteracao_projeto_alter_iteracao_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='iteracao',
            name='status',
            field=models.CharField(choices=[('planejamento', 'Em Planejamento'), ('andamento', 'Em Andamento'), ('concluida', 'Concluída'), ('cancelada', 'Cancelada')], default='planejamento', max_length=20),
        ),
    ]
