# Generated by Django 5.0.3 on 2024-10-26 18:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('iteracao', '0003_remove_release_projeto'),
        ('release', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='iteracao',
            name='relase',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='release.release'),
        ),
        migrations.DeleteModel(
            name='Release',
        ),
    ]
