# Generated by Django 5.0.3 on 2024-04-07 19:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('iteracao', '0004_alter_iteracao_status'),
    ]

    operations = [
        migrations.RenameField(
            model_name='iteracao',
            old_name='gerente',
            new_name='lider',
        ),
        migrations.AlterField(
            model_name='iteracao',
            name='status',
            field=models.CharField(choices=[('criada', 'Criada'), ('andamento', 'Em Andamento'), ('concluida', 'Concluída'), ('cancelada', 'Cancelada')], default='criada', max_length=20),
        ),
    ]
