# Generated by Django 5.0.3 on 2024-10-26 19:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fluxo_etapa', '0001_initial'),
        ('iteracao', '0004_alter_iteracao_relase_delete_release'),
    ]

    operations = [
        migrations.RenameField(
            model_name='iteracao',
            old_name='relase',
            new_name='release',
        ),
        migrations.AddField(
            model_name='iteracao',
            name='etapa',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='fluxo_etapa.fluxoetapa'),
        ),
    ]
