# Generated by Django 5.0.3 on 2024-04-28 00:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('iteracao', '0005_rename_gerente_iteracao_lider_alter_iteracao_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='iteracao',
            name='status',
            field=models.CharField(choices=[('criada', 'Criada'), ('planejamento', 'Em planejamento'), ('andamento', 'Em Andamento'), ('concluida', 'Concluída'), ('cancelada', 'Cancelada')], default='criada', max_length=20),
        ),
    ]
