# Generated by Django 5.0.3 on 2024-10-29 19:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('iteracao', '0005_rename_relase_iteracao_release_iteracao_etapa'),
    ]

    operations = [
        migrations.AlterField(
            model_name='iteracao',
            name='status',
            field=models.CharField(choices=[('criada', 'Criada'), ('andamento', 'Em Andamento'), ('concluida', 'Concluída'), ('cancelada', 'Cancelada')], default='criada', max_length=20),
        ),
    ]
