# Generated by Django 5.0.3 on 2024-05-02 13:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('iteracao', '0006_alter_iteracao_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='iteracao',
            name='descricao',
            field=models.TextField(blank=True, null=True),
        ),
    ]
