# Generated by Django 5.0.3 on 2024-11-20 18:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fluxo_etapa', '0002_fluxoetapa_created_by_fluxoetapa_data_adicao_and_more'),
        ('iteracao', '0006_alter_iteracao_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='iteracao',
            name='etapa',
        ),
        migrations.AddField(
            model_name='iteracao',
            name='etapas',
            field=models.ManyToManyField(blank=True, to='fluxo_etapa.fluxoetapa'),
        ),
        migrations.AlterField(
            model_name='iteracao',
            name='ordem',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='iteracao',
            name='status',
            field=models.CharField(choices=[('pendente', 'Pendente'), ('andamento', 'Em Andamento'), ('concluida', 'Concluída'), ('cancelada', 'Cancelada')], default='pendente', max_length=20),
        ),
    ]
