# Generated by Django 5.0.3 on 2024-05-12 18:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('iteracao', '0007_alter_iteracao_descricao'),
    ]

    operations = [
        migrations.RenameField(
            model_name='iteracao',
            old_name='data_fim',
            new_name='data_termino',
        ),
    ]
