# Generated by Django 5.0.3 on 2024-11-20 20:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('iteracao', '0007_remove_iteracao_etapa_iteracao_etapas_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='iteracao',
            name='status',
            field=models.CharField(choices=[('pendente', 'Pendente'), ('andamento', 'Em Andamento'), ('concluida', 'Concluída'), ('cancelada', 'Cancelada'), ('bloqueada', 'Bloqueada')], default='pendente', max_length=20),
        ),
    ]
