# Generated by Django 5.0.3 on 2025-03-25 19:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('iteracao', '0009_alter_iteracao_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='iteracao',
            name='data_inicio',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='iteracao',
            name='data_termino',
            field=models.DateField(blank=True, null=True),
        ),
    ]
