# Generated by Django 5.0.3 on 2024-03-19 13:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comentario', '0001_initial'),
        ('documento', '0002_remove_documento_conteudo_markdown_documento_caminho_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='comentario',
            name='documento',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='documento.documento'),
        ),
    ]
