# Generated by Django 5.0.3 on 2024-05-07 17:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('artefato', '0003_rename_id_github_artefato_id_file_and_more'),
        ('comentario', '0001_initial'),
        ('membro_projeto', '0013_alter_funcaomembroprojetoatual_data_inicio'),
        ('tarefa', '0021_tarefa_tipo'),
    ]

    operations = [
        migrations.CreateModel(
            name='ComentarioArtefato',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('texto', models.TextField()),
                ('data_hora', models.DateTimeField(auto_now_add=True)),
                ('artefato', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='artefato.artefato')),
                ('autor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='membro_projeto.membroprojeto')),
                ('comentario_pai', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='respostas', to='comentario.comentarioartefato')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ComentarioTarefa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('texto', models.TextField()),
                ('data_hora', models.DateTimeField(auto_now_add=True)),
                ('autor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='membro_projeto.membroprojeto')),
                ('comentario_pai', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='respostas', to='comentario.comentariotarefa')),
                ('tarefa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tarefa.tarefa')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.DeleteModel(
            name='Comentario',
        ),
    ]
