# Generated by Django 5.0.3 on 2025-04-28 21:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0001_initial'),
        ('projeto', '0004_projeto_coordenador'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chat',
            name='projeto',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='projeto.projeto', unique=True),
        ),
    ]
