# Generated by Django 5.0.3 on 2025-04-28 21:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0002_alter_chat_projeto'),
        ('projeto', '0004_projeto_coordenador'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chat',
            name='projeto',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='projeto.projeto'),
        ),
    ]
